<?xml version="1.0" encoding="utf-8" ?>
<!--文档类型  根标签名字  网络上的dtd  dtd名称  dtd的路径-->
<!--<!DOCTYPE stus PUBLIC "//UNKNOWN"  "unknown.dtd">-->

<!--引入本地的DTD ：根标签名字  引入本地的DTD  dtd的文职-->
<!DOCTYPE stus SYSTEM  "stus.dtd">
<!--<!DOCTYPE stus[-->

<!--xml文档里面直接嵌入dtd的约束法则-->
<!--<!DOCTYPE stus [
        <!ELEMENT stus (stu)>
        <!ELEMENT stu (name,age)>
        <!ELEMENT name (#PCDATA)>
        <!ELEMENT age (#PCDATA)>
        ]>-->

<stus>
    <stu id="10086">
        <name>张三</name>
        <age>18</age>

    </stu>
    <stu id="10087">
        <name>张三</name>
        <age>18</age>

    </stu>

</stus>